matrix = matrix()
matrix = c(1,2,3,4,5,6,7,8,9)
matrixrow = matrix(matrix,nrow = 3, ncol = 3, byrow = TRUE)
matrixcol = matrix(matrix,nrow = 3, ncol = 3, byrow = FALSE)
print(matrixrow)
print(matrixcol)
